apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/mongo-root-password
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
            - name: mongo-config
              mountPath: /config
              subPath: mongo.conf
            - name: mongo-credentials
              mountPath: /etc/mongo-credentials
              readOnly: true
      volumes:
        - name: mongo-config
          configMap:
            name: mongo-config
        - name: mongo-credentials
          secret:
            secretName: mongo-credentials
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
