apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
data:
  mongo-root-username: YWRtaW4= # base64 untuk 'admin'
  mongo-root-password: c3VwZXJzZWNyZXRwYXNzd29yZA== # base64 untuk 'supersecretpassword'
